In [3]:
import math
import numpy as np
import time

# 5 #

In [4]:
U = np.array([[1, 2, 6, -1],
             [0, 3, 1, 0],
             [0, 0, 4, -1],
             [0, 0, 0, 2]])
b = np.array([-1, -3, -2, 4])

In [5]:
def upper(U, b, tol=1e-8):
    n, m = U.shape
    if n != m or n != b.shape[0]:
        raise TypeError('Matrix and vector dimensions do not match')

    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        if abs(U[i, i]) < tol:
            raise ValueError('Pivot < tolerance')
        x[i] = (b[i] - sum(U[i, i + 1:] * x[i + 1:])) / U[i, i]
    return x

In [8]:
def upper2(U, b, tol=1e-8):
    n, m = U.shape
    if n != m or n != b.shape[0]:
        raise TypeError('Matrix and vector dimensions do not match')

    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        if abs(U[i, i]) < tol:
            raise ValueError('Pivot < tolerance')
        x[i] = (b[i] - np.dot(U[i, i + 1:], x[i + 1:])) / U[i, i]
    return x

In [9]:
x = upper2(U, b)
x, U @ x

(array([ 3., -1.,  0.,  2.]), array([-1., -3., -2.,  4.]))

In [6]:
sizes = [100, 200, 400, 800]

for n in sizes:
    rU = np.triu(np.random.uniform(-10, 10, (n, n)))
    rb = np.random.uniform(-10, 10, n)

    start = time.time()
    upper(rU, rb)
    end = time.time()

    print(f'{n}: {end - start}s')

100: 0.0006403923034667969s
200: 0.0015716552734375s
400: 0.0052716732025146484s
800: 0.019866228103637695s


# 6 #

In [7]:
A = np.array([[6, 2, 1, -1],
             [2, 4, 1, 0],
             [1, 1, 4, -1],
             [-1, 0, -1, 3]])

In [8]:
def LU(A, tol=1e-8):
    n = A.shape[0]
    L, U = np.zeros((n, n)), np.zeros((n, n))
    
    U[0, :] = A[0, :]
    
    if abs(U[0, 0]) < tol:
        raise ValueError('Pivot < tolerance')
    L[1:, 0] = A[1:, 0] / U[0, 0]
    L[range(n), range(n)] = 1
    
    for i in range(1, n):
        for j in range(i):
            if abs(U[j, j]) < tol:
                raise ValueError('Pivot < tolerance')
            L[i, j] = (A[i, j] - sum(L[i, 0:j] * U[0:j, j])) / U[j, j]
        for j in range(i, n):
            U[i, j] = A[i, j] - sum(L[i, 0:i] * U[0:i, j])
    return L, U

In [9]:
L, U = LU(A)
L, U, L @ U

(array([[ 1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.33333333,  1.        ,  0.        ,  0.        ],
        [ 0.16666667,  0.2       ,  1.        ,  0.        ],
        [-0.16666667,  0.1       , -0.24324324,  1.        ]]),
 array([[ 6.        ,  2.        ,  1.        , -1.        ],
        [ 0.        ,  3.33333333,  0.66666667,  0.33333333],
        [ 0.        ,  0.        ,  3.7       , -0.9       ],
        [ 0.        ,  0.        ,  0.        ,  2.58108108]]),
 array([[ 6.00000000e+00,  2.00000000e+00,  1.00000000e+00,
         -1.00000000e+00],
        [ 2.00000000e+00,  4.00000000e+00,  1.00000000e+00,
          0.00000000e+00],
        [ 1.00000000e+00,  1.00000000e+00,  4.00000000e+00,
         -1.00000000e+00],
        [-1.00000000e+00,  5.55111512e-18, -1.00000000e+00,
          3.00000000e+00]]))

In [10]:
sizes = [100, 200, 400, 800]

for n in sizes:
    rA = np.random.uniform(-10, 10, (n, n))

    start = time.time()
    LU(rA)
    end = time.time()

    print(f'{n}: {end - start}s')

100: 0.038565635681152344s
200: 0.2343449592590332s
400: 1.5185654163360596s
800: 10.984285831451416s
